### ISSUE TITLE
Exception: Path too long exception when extracting a zip ball

### ISSUE THREAD

**Issue by cvrajeesh** [cvrajeesh/SourceCodeReader#1]
PTLE is thrown from GitHubSourceCodeProviderService.

Stack trace

```
ERROR, An error has occured while getting the content for path  from project eugeneagafonov/ConferenceDemos System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
   at System.IO.Path.GetDirectoryName(String path)
   at Ionic.Zip.ZipEntry.InternalExtract(String baseDir, Stream outstream, String password)
   at Ionic.Zip.ZipEntry.Extract(String baseDirectory)
   at Ionic.Zip.ZipFile._InternalExtractAll(String path, Boolean overrideExtractExistingProperty)
   at Ionic.Zip.ZipFile.ExtractAll(String path, ExtractExistingFileAction extractExistingFile)
   at SourceCodeReader.Web.Services.GitHub.GitHubSourceCodeProviderService.ExtractZipBall(String zipFileToExtract, String destinationDirectory) in d:\temp\c0jni425.uhe\input\SourceCodeReader.Web\Services\GitHub\GitHubSourceCodeProviderService.cs:line 216
   at SourceCodeReader.Web.Services.GitHub.GitHubSourceCodeProviderService.GetContent(String username, String project, String path, ISourceCodeOpeningProgress openingProgressListener) in d:\temp\c0jni425.uhe\input\SourceCodeReader.Web\Services\GitHub\GitHubSourceCodeProviderService.cs:line 74
```

**Comment by cvrajeesh** [comment]
Changes committed 
https://github.com/cvrajeesh/SourceCodeReader/commit/af1dee3ef4650008f74de49813539f74971a404a

This is not a perfect fix but solves most of the PathTooLong Exception scenarios. There is a chance that projects with long name could still throw this excetion

**Comment by cvrajeesh** [comment]
@GabrielNar89  how it can fix PTLE?, I am aware that it's a windows bug.

**Comment by gamicklisafisher** [comment]
For copying and deleting “Long Path Tool” software should be try, many articles refer this for such solutions.
